#!/usr/bin/env python3
"""Jak 2's ocean maps of Dead Town and of the mountain, for Jak 3.

Jak 2 draws the sea of Dead Town (ruins) and the stream of the mountain with their own ocean maps,
*ocean-map-ruins* and *ocean-map-mountain*, defined in their level code (levels/ruins/ruins-ocean.gc
and levels/mountain/mountain-ocean.gc). The ocean types are identical in both games, except that
Jak 3's ocean-map has no ocean-spheres field: this copies the tables, renamed, without the spheres,
into the level code of hj2-ruins and hj2-mount (HJR, HJM). Their level-load-info names the map
(:ocean, jak2-haven-city-levels.gc); the level defines it each time it loads, like Jak 2's.

The city's map (*ocean-map-havenj2*, havenj2-ocean.gc in GAME) was copied the same way from Jak 2's
engine/gfx/ocean/ocean-tables.gc.

Run from the repository root: python custom_assets/jak3/levels/havenj2/gen_havenj2_ocean.py
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_util import write_if_changed  # noqa: E402

# (Jak 2 source, Jak 2 name, our level, our map name, DGO)
MAPS = [
    ("goal_src/jak2/levels/ruins/ruins-ocean.gc", "ruins", "hj2-ruins", "*ocean-map-hj2-ruins*",
     "HJR"),
    ("goal_src/jak2/levels/mountain/mountain-ocean.gc", "mountain", "hj2-mount",
     "*ocean-map-hj2-mount*", "HJM"),
]
OUT_DIR = "goal_src/jak3/levels/havenj2"


def top_level_forms(text):
    """(start, end) of each top-level form of a GOAL file."""
    forms = []
    depth = 0
    start = None
    i = 0
    in_string = False
    while i < len(text):
        c = text[i]
        if in_string:
            if c == "\\":
                i += 1
            elif c == '"':
                in_string = False
        elif c == ";":
            i = text.index("\n", i) if "\n" in text[i:] else len(text)
            continue
        elif c == '"':
            in_string = True
        elif c == "(":
            if depth == 0:
                start = i
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                forms.append((start, i + 1))
        i += 1
    return forms


def convert(src, jak2_name, level, map_name, dgo):
    text = open(src, encoding="utf-8").read()
    body = text[text.index(";; DECOMP BEGINS") + len(";; DECOMP BEGINS"):] \
        if ";; DECOMP BEGINS" in text else text
    kept = []
    for start, end in top_level_forms(body):
        form = body[start:end]
        # Jak 3's ocean-map has no ocean-spheres
        if f"*ocean-spheres-{jak2_name}*" in form:
            continue
        if form.startswith("(in-package"):
            continue
        kept.append(form)
    out = "\n\n".join(kept)
    out = out.replace(f"*ocean-map-{jak2_name}*", map_name)
    out = re.sub(r"\*ocean-([a-z-]+)-" + re.escape(jak2_name) + r"\*",
                 lambda m: f"*{level}-ocean-{m.group(1)}*", out)
    name = f"{level}-ocean"
    header = f""";;-*-Lisp-*-
(in-package goal)

;; name: {name}.gc
;; name in dgo: {name}
;; dgos: {dgo}

;; og:jak2-haven-city GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_ocean.py, edit the
;; script. Jak 2's ocean map of {jak2_name} ({map_name}), copied from
;; {src}
;; without its ocean-spheres (Jak 3's ocean-map has none). {level}'s level-load-info names it.

"""
    path = f"{OUT_DIR}/{name}.gc"
    write_if_changed(path, header + out + "\n")
    return path


def main():
    for src, jak2_name, level, map_name, dgo in MAPS:
        print("wrote", convert(src, jak2_name, level, map_name, dgo))


if __name__ == "__main__":
    main()
