;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-forstb: the far end of Haven Forest.
("HJN.DGO"
 (
  "hj2-forstb.go"
  ))
