;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-kiosk: the bazaar's stall, in the market.
("HKH.DGO"
 (
  "hj2-kiosk-part.o"
  "hj2-kiosk.go"
  ))
