;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-fexa: the way out of the fortress, from the prison.
("HKF.DGO"
 (
  "hj2-fort-lift-plat-ag.go"
  "hj2-fexa-obs.o"
  "hj2-fexa.go"
  ))
