;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-fexa: the way out of the fortress, from the prison.
("HKF.DGO"
 (
  "hj2-fort-lift-plat-ag.go"
  "hj2-fexa-obs.o"
  "hj2-fexa.go"
  ))
