;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-hide: the Underground's hideout.
("HJD.DGO"
 (
  "warp-gate-ag.go"
  "hj2-hide-door-b-ag.go"
  "hj2-hide-light-ag.go"
  "hj2-hide-light-fog-ag.go"
  "hj2-hide-obs.o"
  "hj2-hide-part.o"
  "hj2-hide.go"
  ))
