;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-hide: the Underground's hideout.
("HJD.DGO"
 (
  "hip-door-a-ag.go"
  "hj2-hide.go"
  ))
