;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-hide: the Underground's hideout.
("HJD.DGO"
 (
  "hip-door-a-ag.go"
  "warp-gate-ag.go"
  "hj2-hide.go"
  ))
