;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-genc: Haven City's district ctygenc: the main town, by the stadium.
("HNC.DGO"
 (
  "hj2-genc.go"
  ))
