;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-onin: Onin's tent, in the market.
("HKI.DGO"
 (
  "hj2-onin-part.o"
  "hj2-onin.go"
  ))
