;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-ruins: Dead Town, through the slums airlock.
("HJR.DGO"
 (
  "com-airlock-outer-ag.go"
  "hj2-ruins.go"
  ))
