;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-ruins: Dead Town and the Sage's hut, through the slums airlock.
("HJR.DGO"
 (
  "com-airlock-outer-ag.go"
  "hj2-ruins-beam-ag.go"
  "hj2-ruins-ocean.o"
  "hj2-ruins-obs.o"
  "hj2-ruins-part.o"
  "hj2-ruins.go"
  ))
