;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-slma: Haven City's district ctysluma: the slums, by the hideout.
("HSA.DGO"
 (
  "security-wall-ag.go"
  "cty-fruit-stand-ag.go"
  "hj2-propa-ag.go"
  "hj2-propa-damaged-ag.go"
  "hj2-propa-broken-ag.go"
  "hj2-hide-door-a-ag.go"
  "hj2-fort-gate-ag.go"
  "hj2-cty-guard-turret-ag.go"
  "hj2-cty-guard-turret-explode-ag.go"
  "hj2-slma.go"
  ))
