;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-mtnx: the outside of the mountain temple, seen from the mountain top.
("HJX.DGO"
 (
  "hj2-mtnx.go"
  ))
