;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-mtnx: the outside of the mountain temple, seen from the mountain top.
("HJX.DGO"
 (
  "hj2-mtnx.go"
  ))
