;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-mtnx: the outside of the mountain temple, seen from the mountain top.
("HJX.DGO"
 (
  "hj2-mtn-plat-buried-ag.go"
  "hj2-mtn-button-ag.go"
  "hj2-mtn-dice-button-ag.go"
  "hj2-mtn-plat-eject-ag.go"
  "hj2-mtn-lens-ag.go"
  "hj2-mtn-dice-ag.go"
  "hj2-trans-plat-ag.go"
  "hj2-mtn-aval-rocks-ag.go"
  "hj2-mtnx-obs.o"
  "hj2-mtnx.go"
  ))
