;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-genb: Haven City's district ctygenb: the main town, by the cable pillar.
("HNB.DGO"
 (
  "hj2-airlock-outer-ag.go"
  "hj2-genb.go"
  ))
