;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-atollx: the way to the pumping station, from the slums airlock.
("HJA.DGO"
 (
  "com-airlock-inner-ag.go"
  "hj2-atollx.go"
  ))
