;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-atollx: the way to the pumping station, from the slums airlock.
("HJA.DGO"
 (
  "com-airlock-inner-ag.go"
  "hj2-atollx.go"
  ))
