#!/usr/bin/env python3
"""
Register or package OpenGOAL Texture Pack archives (.zip) into index.json under "texturePacks".

Primary Workflow (Default):
  Scans/recovers launcher-compliant .zip archives from:
    docs/modding/current_mod/texture_packs/
  (as generated by the OpenGOAL Texture Pack Generator GUI tool, or placed manually),
  inspects their internal metadata.json, computes SHA256 checksums, and updates index.json.

Alternative Workflow (--from-source):
  Builds a new .zip archive directly from raw PNG textures in:
    custom_assets/<game>/texture_replacements/
  and saves it into docs/modding/current_mod/texture_packs/ before updating index.json.

Complies with:
- Official OpenGOAL documentation: https://opengoal.dev/docs/developing/texture_packs/
- Official OpenGOAL launcher schema: schemas/texture-packs/v1/texture-pack-schema.v1.json
- Official OpenGOAL launcher backend: src-tauri/src/commands/features/texture_packs.rs

Can be run standalone or via Taskfile:
    task modding-package-texture-pack
    task modding-register-texture-pack
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import zipfile

REPO_ROOT = Path(__file__).resolve().parents[2]


def run_git(args: list[str]) -> str:
  """Run a git command in REPO_ROOT and return stripped stdout."""
  try:
    res = subprocess.run(
        ["git"] + args,
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return res.stdout.strip()
  except Exception:
    return ""


def detect_current_branch() -> str:
  return run_git(["rev-parse", "--abbrev-ref", "HEAD"]) or "master-dev"


def detect_github_repo_info() -> tuple[str, str]:
  """Return (owner, repo_name) of the repository the current branch publishes to: the mod
  repository for mods/<name>, origin otherwise."""
  branch = detect_current_branch()
  remote = run_git(["config", "--get", f"branch.{branch}.remote"]) or "origin"
  remote_url = run_git(["remote", "get-url", remote])
  match = re.search(r"github\.com[/:]([\w.-]+)/([\w.-]+?)(?:\.git)?$", remote_url)
  if match:
    return (match.group(1), match.group(2))
  raise SystemExit(f"{remote} is not a GitHub repository: the texture pack URLs point at it.")


def published_branch() -> str:
  """The current branch's name on GitHub: mods/<name> publishes to its repository's main."""
  branch = detect_current_branch()
  merge = run_git(["config", "--get", f"branch.{branch}.merge"])
  return merge.replace("refs/heads/", "", 1) if merge else branch


def mod_repo_slug() -> str | None:
  """The catalog key of the mod on a mods/<name> branch: the single key of its index.json."""
  try:
    mods = json.loads((REPO_ROOT / "index.json").read_text(encoding="utf-8")).get("mods") or {}
  except (OSError, ValueError):
    return None
  return next(iter(mods)) if len(mods) == 1 else None


def detect_active_game() -> str:
  """Auto-detect active game from branch, .env, or custom_assets/."""
  branch = detect_current_branch()
  for candidate in ["jak1", "jak2", "jak3", "jakx"]:
    if branch.startswith((f"{candidate}/", f"mods/{candidate}-")):
      return candidate

  env_file = REPO_ROOT / "scripts" / "tasks" / ".env"
  if env_file.exists():
    try:
      for line in env_file.read_text(encoding="utf-8").splitlines():
        if line.startswith("GAME="):
          game_val = line.split("=", 1)[1].strip().strip('"').strip("'")
          if game_val in ["jak1", "jak2", "jak3", "jakx"]:
            return game_val
    except Exception:
      pass

  for candidate in ["jak1", "jak2", "jak3"]:
    tex_dir = REPO_ROOT / "custom_assets" / candidate / "texture_replacements"
    if tex_dir.exists() and list(tex_dir.rglob("*.png")):
      return candidate

  return "jak2"


def detect_author() -> str:
  git_user = run_git(["config", "user.name"])
  if git_user and git_user.strip():
    return git_user.strip()
  owner, _ = detect_github_repo_info()
  return owner


def compute_sha256(filepath: Path) -> str:
  hasher = hashlib.sha256()
  with open(filepath, "rb") as f:
    while chunk := f.read(65536):
      hasher.update(chunk)
  return hasher.hexdigest()


def slug_to_display_name(slug: str) -> str:
  clean = slug.replace("-textures", "").replace("_textures", "")
  words = [w.capitalize() for w in re.split(r"[-_]+", clean) if w]
  return " ".join(words) + " Textures"


def derive_release_download_url(
    zip_name: str,
    slug: str,
    version: str,
    branch: str,
    repo_owner: str,
    repo_name: str,
    release_url_base: str | None = None,
) -> str:
  """Build public GitHub release download URL for texture pack zip."""
  if release_url_base:
    return f"{release_url_base.rstrip('/')}/{zip_name}"

  # A mod repository (mods/<name>) releases as <catalog key>-vX.Y.Z.
  if branch.startswith("mods/") and mod_repo_slug():
    release_tag = f"{mod_repo_slug()}-v{version}"
  # If on a mod branch like jak2/features/blue-krimzon-guard, use the mod release tag
  elif branch.startswith(("jak1/", "jak2/", "jak3/", "jakx/")) and "/" in branch:
    mod_leaf = branch.split("/")[-1]
    release_tag = f"{mod_leaf}-v{version}"
  else:
    base_slug = slug.replace("-textures", "")
    release_tag = f"{base_slug}-v{version}"

  return f"https://github.com/{repo_owner}/{repo_name}/releases/download/{release_tag}/{zip_name}"


def register_texture_pack_zip(
    zip_path: Path,
    update_index: bool = True,
    release_url_base: str | None = None,
    default_game: str | None = None,
) -> dict:
  """Inspect a single .zip archive and update index.json with its metadata."""
  if not zip_path.exists():
    raise FileNotFoundError(f"Texture pack zip not found: {zip_path}")

  branch = detect_current_branch()
  owner, repo_name = detect_github_repo_info()
  detected_game = default_game or detect_active_game()
  checksum = compute_sha256(zip_path)

  meta = {}
  try:
    with zipfile.ZipFile(zip_path, "r") as zf:
      if "metadata.json" in zf.namelist():
        meta = json.loads(zf.read("metadata.json").decode("utf-8"))
  except Exception as err:
    print(f"[-] Warning: could not read metadata.json in {zip_path.name}: {err}")

  # 1. Derive slug from zip filename
  base_slug = zip_path.stem.lower()
  base_slug = re.sub(r"-v\d+.*$", "", base_slug)
  base_slug = re.sub(r"[^a-z0-9_-]+", "-", base_slug).strip("-")
  if not base_slug.endswith("-textures"):
    base_slug = f"{base_slug}-textures"

  # 2. Extract metadata with fallbacks
  tp_name = meta.get("name") or meta.get("displayName") or slug_to_display_name(base_slug)
  ver_match = re.search(r"(\d+\.\d+\.\d+)", zip_path.name)
  tp_version = meta.get("version") or (ver_match.group(1) if ver_match else "1.0.0")
  tp_author = meta.get("author") or meta.get("authors") or detect_author()
  tp_authors = [tp_author] if isinstance(tp_author, str) else [str(a) for a in tp_author]
  tp_desc = meta.get("description") or f"Texture replacement pack for {tp_name} ({detected_game})."
  tp_tags = meta.get("tags") or [detected_game, "retexture"]
  if isinstance(tp_tags, list):
    branch_m = re.match(r"^jak[123]/(?:features|config)/(.+)$", branch)
    mod_slug = (branch_m.group(1).replace("/", "-").replace("_", "-") if branch_m
                else mod_repo_slug() if branch.startswith("mods/") else None)
    if mod_slug and mod_slug not in tp_tags:
      tp_tags.append(mod_slug)
  tp_supported = meta.get("supportedGames") or [detected_game]

  now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
  published_date = meta.get("publishedDate") or now_iso

  download_url = derive_release_download_url(
      zip_name=zip_path.name,
      slug=base_slug,
      version=tp_version,
      branch=branch,
      repo_owner=owner,
      repo_name=repo_name,
      release_url_base=release_url_base,
  )

  # Check cover candidate URLs
  web_branch = published_branch()
  cover_url = (
      f"https://raw.githubusercontent.com/{owner}/{repo_name}/{web_branch}/docs/img/mod/mod_cover.png"
  )
  website_url = f"https://github.com/{owner}/{repo_name}/tree/{web_branch}"

  pack_info = {
      "slug": base_slug,
      "displayName": tp_name,
      "version": tp_version,
      "authors": tp_authors,
      "description": tp_desc,
      "tags": tp_tags,
      "supportedGames": tp_supported,
      "downloadUrl": download_url,
      "sha256": checksum,
  }

  print(f"[+] Processed archive: {zip_path.name}")
  print(f"    - Slug:         {base_slug}")
  print(f"    - Display Name: {tp_name}")
  print(f"    - Version:      {tp_version}")
  print(f"    - Authors:      {', '.join(tp_authors)}")
  print(f"    - SHA256:       {checksum}")
  print(f"    - Download URL: {download_url}")

  if update_index:
    index_path = REPO_ROOT / "index.json"
    if not index_path.exists():
      catalog = {"schemaVersion": "1.0.0", "sourceName": "OpenGOAL Mods", "texturePacks": {}}
    else:
      try:
        with open(index_path, "r", encoding="utf-8") as f:
          catalog = json.load(f)
      except Exception as e:
        print(f"[-] Could not parse existing index.json: {e}")
        catalog = {"schemaVersion": "1.0.0", "sourceName": "OpenGOAL Mods", "texturePacks": {}}

    if "texturePacks" not in catalog or not isinstance(catalog["texturePacks"], dict):
      catalog["texturePacks"] = {}

    if base_slug not in catalog["texturePacks"]:
      catalog["texturePacks"][base_slug] = {
          "displayName": tp_name,
          "description": tp_desc,
          "authors": tp_authors,
          "tags": tp_tags,
          "supportedGames": tp_supported,
          "websiteUrl": website_url,
          "coverArtUrl": cover_url,
          "thumbnailArtUrl": cover_url,
          "versions": [],
      }

    entry = catalog["texturePacks"][base_slug]
    entry["displayName"] = tp_name
    entry["description"] = tp_desc
    entry["authors"] = tp_authors
    entry["tags"] = tp_tags
    entry["supportedGames"] = tp_supported
    entry["websiteUrl"] = website_url
    if cover_url:
      entry["coverArtUrl"] = cover_url
      entry["thumbnailArtUrl"] = cover_url

    new_version_obj = {
        "version": tp_version,
        "publishedDate": published_date,
        "supportedGames": tp_supported,
        "assets": {
            "windows": download_url,
            "linux": download_url,
            detected_game: download_url,
        },
        "checksums": {
            "windows": checksum,
            "linux": checksum,
            detected_game: checksum,
        },
    }

    # Replace existing version entry or prepend
    entry["versions"] = [v for v in entry.get("versions", []) if v.get("version") != tp_version]
    entry["versions"].insert(0, new_version_obj)
    catalog["lastUpdated"] = now_iso

    try:
      with open(index_path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, indent=2, ensure_ascii=False)
        f.write("\n")
      print(f"[+] Successfully registered texture pack '{base_slug}' in {index_path.name}")
    except Exception as err:
      print(f"[-] Failed writing to index.json: {err}")

  return pack_info


def scan_and_register_texture_packs(
    dir_path: Path | None = None,
    specific_zip: Path | None = None,
    update_index: bool = True,
    release_url_base: str | None = None,
    default_game: str | None = None,
) -> list[dict]:
  """Primary entrypoint: scans docs/modding/current_mod/texture_packs/ and registers zips."""
  if specific_zip:
    if not specific_zip.exists():
      raise FileNotFoundError(f"Specified archive not found: {specific_zip}")
    return [
        register_texture_pack_zip(
            zip_path=specific_zip,
            update_index=update_index,
            release_url_base=release_url_base,
            default_game=default_game,
        )
    ]

  if dir_path is None:
    dir_path = REPO_ROOT / "docs" / "modding" / "current_mod" / "texture_packs"

  if not dir_path.exists():
    dir_path.mkdir(parents=True, exist_ok=True)

  zips = [
      p for p in dir_path.glob("*.zip")
      if not (p.name.startswith("windows-") or p.name.startswith("linux-"))
  ]

  if not zips:
    print(f"[-] No texture pack .zip archive found in {dir_path}")
    print("[!] Please build your texture pack using the OpenGOAL Texture Pack Generator GUI first:")
    print("      https://github.com/whozghiar/open-goal-texture-pack-generator")
    print(f"[!] Or export/place your .zip archive inside:\n      {dir_path}")
    print("[!] (To build directly from raw custom_assets/ instead, pass --from-source)")
    return []

  print(f"[+] Found {len(zips)} texture pack archive(s) in {dir_path}")
  results = []
  for zp in sorted(zips):
    res = register_texture_pack_zip(
        zip_path=zp,
        update_index=update_index,
        release_url_base=release_url_base,
        default_game=default_game,
    )
    results.append(res)

  return results


def build_texture_pack_from_source(
    game: str | None = None,
    slug: str | None = None,
    display_name: str | None = None,
    description: str | None = None,
    author: str | None = None,
    version: str = "1.0.0",
    tags: list[str] | None = None,
    cover_path: Path | None = None,
    output_zip: Path | None = None,
    update_index: bool = True,
    release_url_base: str | None = None,
) -> Path:
  """Legacy / alternative workflow: package directly from custom_assets/ PNGs."""
  if not game:
    game = detect_active_game()

  branch = detect_current_branch()

  if not slug:
    leaf = branch.split("/")[-1] if "/" in branch else "custom"
    if not leaf.endswith("-textures"):
      slug = f"{leaf}-textures"
    else:
      slug = leaf

  if not display_name:
    display_name = slug_to_display_name(slug)

  if not author:
    author = detect_author()

  if not description:
    description = f"Texture replacement pack for {display_name} ({game})."

  if tags is None:
    tags = [game, "retexture"]
    keywords = [k for k in re.split(r"[-_]+", slug) if k not in ["textures", game, "jak"]]
    for k in keywords[:3]:
      if k not in tags:
        tags.append(k)

  src_texture_dir = REPO_ROOT / "custom_assets" / game / "texture_replacements"
  if not src_texture_dir.exists():
    raise FileNotFoundError(f"Texture directory not found: {src_texture_dir}")

  png_files = list(src_texture_dir.rglob("*.png"))
  if not png_files:
    raise ValueError(f"No PNG textures found in {src_texture_dir}")

  print(f"[+] Compiling {len(png_files)} texture(s) for {game} from {src_texture_dir}")

  if output_zip is None:
    output_dir = REPO_ROOT / "docs" / "modding" / "current_mod" / "texture_packs"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_zip = output_dir / f"{slug}-v{version}.zip"
  else:
    output_zip.parent.mkdir(parents=True, exist_ok=True)

  now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
  release_date_simple = datetime.now(timezone.utc).strftime("%Y-%m-%d")

  metadata = {
      "schemaVersion": "1.0.0",
      "version": version,
      "name": display_name,
      "description": description,
      "author": author,
      "authors": author,
      "releaseDate": release_date_simple,
      "publishedDate": now_iso,
      "tags": tags,
      "supportedGames": [game],
  }

  print(f"[+] Creating texture pack archive: {output_zip}")
  with zipfile.ZipFile(output_zip, "w", zipfile.ZIP_DEFLATED) as zf:
    metadata_bytes = json.dumps(metadata, indent=2, ensure_ascii=False).encode("utf-8")
    zf.writestr("metadata.json", metadata_bytes)
    print("  [+] Added metadata.json")

    cover_file = None
    if cover_path and cover_path.exists():
      cover_file = cover_path
    else:
      candidates = [
          REPO_ROOT / "docs" / "img" / "mod" / "mod_cover.png",
          REPO_ROOT / "docs" / "img" / "mod" / "cover.png",
          REPO_ROOT / "custom_assets" / game / "cover.png",
      ]
      for c in candidates:
        if c.exists():
          cover_file = c
          break

    if cover_file:
      zf.write(cover_file, arcname="cover.png")
      print(f"  [+] Added cover.png from {cover_file}")

    for png in sorted(png_files):
      rel_path = png.relative_to(REPO_ROOT)
      arcname = str(rel_path).replace("\\", "/")
      zf.write(png, arcname=arcname)
      print(f"  [+] Added {arcname}")

  # Register the newly created zip
  register_texture_pack_zip(
      zip_path=output_zip,
      update_index=update_index,
      release_url_base=release_url_base,
      default_game=game,
  )

  return output_zip


def main():
  parser = argparse.ArgumentParser(
      description=(
          "Register or package OpenGOAL Texture Pack archives (.zip) into index.json.\n"
          "By default, scans docs/modding/current_mod/texture_packs/ for archives built\n"
          "via the OpenGOAL Texture Pack Generator GUI tool."
      )
  )
  parser.add_argument(
      "--zip",
      type=Path,
      default=None,
      help="Specific texture pack .zip file to register",
  )
  parser.add_argument(
      "--dir",
      type=Path,
      default=None,
      help="Directory to scan for .zip archives (default: docs/modding/current_mod/texture_packs/)",
  )
  parser.add_argument(
      "--from-source",
      action="store_true",
      help="Force building a new .zip from custom_assets/<game>/texture_replacements/ PNG files",
  )
  parser.add_argument(
      "--no-index",
      action="store_true",
      help="Inspect archive and compute checksums without writing to index.json",
  )
  parser.add_argument(
      "--release-url",
      default=None,
      help="Custom GitHub release base URL for downloads",
  )
  parser.add_argument(
      "--game",
      choices=["jak1", "jak2", "jak3", "jakx"],
      default=None,
      help="Game identifier (jak1|jak2|jak3|jakx)",
  )
  # Legacy options for --from-source mode
  parser.add_argument("--slug", default=None, help="Slug for --from-source mode")
  parser.add_argument("--display-name", default=None, help="Display name for --from-source mode")
  parser.add_argument("--description", default=None, help="Description for --from-source mode")
  parser.add_argument("--author", default=None, help="Author for --from-source mode")
  parser.add_argument("--version", default="1.0.0", help="Version for --from-source mode")
  parser.add_argument("--tags", nargs="+", default=None, help="Tags for --from-source mode")
  parser.add_argument("--cover", type=Path, default=None, help="Cover art for --from-source mode")
  parser.add_argument("--output", type=Path, default=None, help="Output zip for --from-source mode")
  parser.add_argument(
      "--update-index",
      action="store_true",
      help="Kept for backwards compatibility (index is updated by default)",
  )

  args = parser.parse_args()
  update_index = not args.no_index

  if args.from_source:
    build_texture_pack_from_source(
        game=args.game,
        slug=args.slug,
        display_name=args.display_name,
        description=args.description,
        author=args.author,
        version=args.version,
        tags=args.tags,
        cover_path=args.cover,
        output_zip=args.output,
        update_index=update_index,
        release_url_base=args.release_url,
    )
  else:
    scan_and_register_texture_packs(
        dir_path=args.dir,
        specific_zip=args.zip,
        update_index=update_index,
        release_url_base=args.release_url,
        default_game=args.game,
    )


if __name__ == "__main__":
  main()
