;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-pcab: the palace cable, between the pillar tops.
("HJQ.DGO"
 (
  "com-airlock-outer-ag.go"
  "hj2-pcab.go"
  ))
