;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-pcab: the palace cable, between the pillar tops.
("HJQ.DGO"
 (
  "com-airlock-outer-ag.go"
  "hj2-pcab.go"
  ))
