;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-fexb: the end of the way out of the fortress, with its gate to the slums.
("HKG.DGO"
 (
  "hj2-fort-gate-ag.go"
  "hj2-fort-pool-ag.go"
  "hj2-fexb-obs.o"
  "hj2-fexb.go"
  ))
