;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-fexb: the end of the way out of the fortress, with its gate to the slums.
("HKG.DGO"
 (
  "hj2-fort-gate-ag.go"
  "hj2-fort-pool-ag.go"
  "hj2-fexb-obs.o"
  "hj2-fexb-part.o"
  "hj2-fexb.go"
  ))
