;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-markb: Haven City's district ctymarkb: the market, by the gardens.
("HMB.DGO"
 (
  "market-sack-a-ag.go"
  "market-sack-b-ag.go"
  "market-crate-ag.go"
  "market-basket-a-ag.go"
  "market-basket-b-ag.go"
  "cty-fruit-stand-ag.go"
  "hj2-markb.go"
  ))
