;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-stadd: the stadium's race track, behind the stadium grounds.
("HJZ.DGO"
 (
  "hj2-stadd.go"
  ))
