;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-stadd: the stadium's race track, behind the stadium grounds.
("HJZ.DGO"
 (
  "hj2-stadd-part.o"
  "hj2-stadd.go"
  ))
