;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-atoll: the pumping station.
("HJL.DGO"
 (
  "hj2-airlock-outer-ag.go"
  "hj2-piston-ag.go"
  "hj2-turbine-ag.go"
  "hj2-liftcat-ag.go"
  "hj2-atollrotpipe-ag.go"
  "hj2-slider-ag.go"
  "hj2-atoll-windmill-ag.go"
  "hj2-atoll-valve-ag.go"
  "hj2-atoll-hatch-ag.go"
  "hj2-atoll-mar-symbol-ag.go"
  "hj2-gun-buoy-ag.go"
  "hj2-atoll-obs.o"
  "hj2-atoll-part.o"
  "hj2-atoll.go"
  ))
