;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-atoll: the pumping station.
("HJL.DGO"
 (
  "com-airlock-outer-ag.go"
  "hj2-piston-ag.go"
  "hj2-turbine-ag.go"
  "hj2-liftcat-ag.go"
  "hj2-atollrotpipe-ag.go"
  "hj2-slider-ag.go"
  "hj2-atoll-windmill-ag.go"
  "hj2-atoll-valve-ag.go"
  "hj2-atoll-hatch-ag.go"
  "hj2-atoll-mar-symbol-ag.go"
  "hj2-atoll-obs.o"
  "hj2-atoll.go"
  ))
