;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-garage: Keira's garage, behind the stadium grounds.
("HJK.DGO"
 (
  "hj2-garage.go"
  ))
