;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-garage: Keira's garage, behind the stadium grounds.
("HJK.DGO"
 (
  "hj2-garage.go"
  ))
