;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-port: Haven City's district ctyport: the port.
("HPT.DGO"
 (
  "air-train-ag.go"
  "barge-ag.go"
  "security-wall-ag.go"
  "hj2-propa-ag.go"
  "hj2-propa-damaged-ag.go"
  "hj2-propa-broken-ag.go"
  "hj2-hip-door-ag.go"
  "hj2-farthy-ag.go"
  "ctyport-obs.o"
  "hj2-port-obs.o"
  "hj2-port.go"
  ))
