;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-vin: Vin's power station room.
("HJV.DGO"
 (
  "vin-door-ctyinda-ag.go"
  "hj2-vin.go"
  ))
