;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-vin: Vin's power station room.
("HJV.DGO"
 (
  "vin-door-ctyinda-ag.go"
  "hj2-vin.go"
  ))
