;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-vin: Vin's power station room.
("HJV.DGO"
 (
  "warp-gate-ag.go"
  "hj2-vin-door-ag.go"
  "hj2-vin-turbine-ag.go"
  "hj2-vin-obs.o"
  "hj2-vin-part.o"
  "hj2-vin.go"
  ))
