;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-gun: the gun course.
("HJG.DGO"
 (
  "hj2-hip-door-ag.go"
  "hj2-fort-gate-ag.go"
  "hj2-gun-part.o"
  "hj2-gun.go"
  ))
