;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-gun: the gun course.
("HJG.DGO"
 (
  "hip-door-a-ag.go"
  "hj2-gun.go"
  ))
