;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-farmb: Haven City's district ctyfarmb: the gardens, by the market.
("HFB.DGO"
 (
  "farm-chilirots-ag.go"
  "farm-marrow-ag.go"
  "farm-beetree-ag.go"
  "farm-cabbage-ag.go"
  "farm-small-cabbage-ag.go"
  "farm-sprinkler-barrels-ag.go"
  "hj2-yakow-ag.go"
  "hj2-farmb.go"
  ))
