;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-cons: the construction site.
("HJC.DGO"
 (
  "hj2-airlock-outer-ag.go"
  "hj2-cons-silo-doors-ag.go"
  "hj2-cons-bomb-elevator-ag.go"
  "hj2-cons-bomb-hinges-ag.go"
  "hj2-cons-obs.o"
  "hj2-cons-part.o"
  "hj2-cons.go"
  ))
