;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-cons: the construction site.
("HJC.DGO"
 (
  "com-airlock-outer-ag.go"
  "hj2-cons-silo-doors-ag.go"
  "hj2-cons-bomb-elevator-ag.go"
  "hj2-cons-bomb-hinges-ag.go"
  "hj2-cons-obs.o"
  "hj2-cons.go"
  ))
