;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-indb: Haven City's district ctyindb: the industrial section, by the slums.
("HIB.DGO"
 (
  "security-wall-ag.go"
  "hj2-propa-ag.go"
  "hj2-propa-damaged-ag.go"
  "hj2-propa-broken-ag.go"
  "hj2-airlock-outer-ag.go"
  "hj2-cty-guard-turret-ag.go"
  "hj2-cty-guard-turret-explode-ag.go"
  "hj2-indb.go"
  ))
