;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-digb: the far end of the dig.
("HJU.DGO"
 (
  "hj2-digb.go"
  ))
