;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-sage: the Sage's hut, at the far end of Dead Town.
("HJW.DGO"
 (
  "hj2-sage.go"
  ))
