;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-stdm: Haven City's district stadium: the stadium grounds.
("HSD.DGO"
 (
  "hj2-cty-guard-turret-ag.go"
  "hj2-cty-guard-turret-explode-ag.go"
  "hj2-stdm.go"
  ))
