;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-prison: the fortress prison, behind the far gate of the fortress.
("HKE.DGO"
 (
  "hj2-fort-gate-ag.go"
  "hj2-prsn-cell-door-ag.go"
  "hj2-prsn-vent-fan-ag.go"
  "hj2-prsn-torture-ag.go"
  "hj2-prsn-hang-cell-ag.go"
  "hj2-warp-gate-b-ag.go"
  "hj2-prison-obs.o"
  "hj2-prison.go"
  ))
