;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-consb: the tunnel to the construction site, from the industrial section.
("HJB.DGO"
 (
  "vin-door-ctyinda-ag.go"
  "com-airlock-inner-ag.go"
  "hj2-consb.go"
  ))
