;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-consb: the tunnel to the construction site, from the industrial section.
("HJB.DGO"
 (
  "vin-door-ctyinda-ag.go"
  "com-airlock-inner-ag.go"
  "hj2-consb.go"
  ))
