;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-oracle: the Oracle.
("HJO.DGO"
 (
  "cty-door-ag.go"
  "hj2-oracle.go"
  ))
