;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-slmb: Haven City's district ctyslumb: the slums, by the fortress and the Dead Town airlock.
("HSB.DGO"
 (
  "security-wall-ag.go"
  "hj2-propa-ag.go"
  "hj2-propa-damaged-ag.go"
  "hj2-propa-broken-ag.go"
  "hj2-airlock-outer-ag.go"
  "hj2-airlock-inner-ag.go"
  "hj2-fort-gate-ag.go"
  "hj2-cty-guard-turret-ag.go"
  "hj2-cty-guard-turret-explode-ag.go"
  "hj2-slmb.go"
  ))
