;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-dig: the dig.
("HJT.DGO"
 (
  "warp-gate-ag.go"
  "hj2-dig-sinking-plat-ag.go"
  "hj2-dig-tipping-rock-ag.go"
  "hj2-dig-spikey-step-ag.go"
  "hj2-dig-wheel-step-ag.go"
  "hj2-dig-balloon-lurker-ag.go"
  "hj2-dig-log-ag.go"
  "hj2-dig-button-ag.go"
  "hj2-dig-totem-ag.go"
  "hj2-dig-sphere-door-ag.go"
  "hj2-dig-trapeze-ag.go"
  "rigid-body-plat.o"
  "hj2-dig-obs.o"
  "hj2-dig.go"
  ))
