;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-dig: the dig.
("HJT.DGO"
 (
  "warp-gate-ag.go"
  "jak-pole+0-ag.go"
  "hj2-dig-sinking-plat-ag.go"
  "hj2-dig-tipping-rock-ag.go"
  "hj2-dig-spikey-step-ag.go"
  "hj2-dig-wheel-step-ag.go"
  "hj2-dig-balloon-lurker-ag.go"
  "hj2-dig-trapeze-ag.go"
  "hj2-dig-log-ag.go"
  "hj2-dig-button-ag.go"
  "hj2-dig-totem-ag.go"
  "hj2-dig-sphere-door-ag.go"
  "hj2-dig-stomp-block-ag.go"
  "rigid-body-plat.o"
  "hj2-dig-obs.o"
  "hj2-dig-part.o"
  "hj2-dig.go"
  ))
