;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-fortb: the far end of the fortress.
("HJJ.DGO"
 (
  "hj2-fort-gate-ag.go"
  "hj2-fortb.go"
  ))
