;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-fortb: the far end of the fortress.
("HJJ.DGO"
 (
  "hj2-fort-gate-ag.go"
  "hj2-fortb.go"
  ))
