;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-hiphog: the Hip Hog saloon.
("HJH.DGO"
 (
  "hj2-hip-door-ag.go"
  "hj2-hiphog-part.o"
  "hj2-hiphog.go"
  ))
