;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-proof: the palace roof.
("HJP.DGO"
 (
  "com-airlock-outer-ag.go"
  "hj2-proof.go"
  ))
