;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-proof: the palace roof.
("HJP.DGO"
 (
  "hj2-airlock-outer-ag.go"
  "hj2-pal-flip-step-ag.go"
  "hj2-pal-lowrez-throne-ag.go"
  "hj2-pal-prong-ag.go"
  "hj2-proof-part.o"
  "hj2-proof.go"
  ))
