;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-slmc: Haven City's district ctyslumc: the slums, by the pumping station airlock.
("HSC.DGO"
 (
  "hj2-airlock-outer-ag.go"
  "hj2-oracle-door-ag.go"
  "hj2-slmc.go"
  ))
