("FREEHQ.DGO"
 ("freehq-part.o"
  "freehq-scenes.o"
  "tpage-798.go"
  "tpage-1167.go"
  "tpage-1793.go"
  "tpage-939.go"
  "tpage-1464.go"
  "tpage-1035.go"
  "daxter-highres-ag.go"
  "jakc-highres-ag.go"
  "torn-highres-ag.go"
  "freehq-sml-door-ag.go"
  "warp-gate-ag.go" ;; added -- og:jak2-haven-city the time gate to Jak 2's world (jak2-haven-city-world.gc)
  "freehq.go"
 ))
