;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-marka: Haven City's district ctymarka: the market, by the port.
("HMA.DGO"
 (
  "security-wall-ag.go"
  "market-basket-a-ag.go"
  "market-basket-b-ag.go"
  "market-crate-ag.go"
  "market-sack-b-ag.go"
  "market-sack-a-ag.go"
  "cty-fruit-stand-ag.go"
  "hj2-marka.go"
  ))
