;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-farma: Haven City's district ctyfarma: the gardens, by the mountain airlock.
("HFA.DGO"
 (
  "farm-beetree-ag.go"
  "farm-marrow-ag.go"
  "farm-sprinkler-barrels-ag.go"
  "farm-chilirots-ag.go"
  "farm-cabbage-ag.go"
  "farm-small-cabbage-ag.go"
  "hj2-airlock-outer-ag.go"
  "hj2-airlock-inner-ag.go"
  "hj2-farma.go"
  ))
