;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-forest: Haven Forest.
("HJF.DGO"
 (
  "hj2-forest-part.o"
  "hj2-forest.go"
  ))
