;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-mount: the mountain, from the gardens airlock to the way to Haven Forest.
("HJM.DGO"
 (
  "com-airlock-outer-ag.go"
  "warp-gate-ag.go"
  "hj2-trans-plat-ag.go"
  "hj2-iris-door-ag.go"
  "hj2-mtn-elevator-ag.go"
  "hj2-mtn-plat-updown-ag.go"
  "hj2-mtn-plat-long-ag.go"
  "hj2-mtn-plat-shoot-ag.go"
  "hj2-mtn-plat-buried-ag.go"
  "hj2-pal-windmill-ag.go"
  "hj2-mount-ocean.o"
  "hj2-mount-obs.o"
  "hj2-mount.go"
  ))
