;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-pal: Haven City's district ctypal: the palace plaza.
("HPL.DGO"
 (
  "security-wall-ag.go"
  "hj2-airlock-outer-ag.go"
  "hj2-airlock-inner-ag.go"
  "hj2-palace-door-ag.go"
  "hj2-pal.go"
  ))
