"""A port's manifest: which levels of the source game become which levels of the target game, and
everything the steps need to know about the mod (its classes, what it keeps, its level ids...).

A manifest is a .jsonc file (JSON with comments), custom_assets/<target>/ports/<port>/port.jsonc.
scripts/level_port/README.md describes its keys.
"""

import importlib
import os

from .common import files
from .common.files import read_jsonc


class Level:
    """One level of the port (a target game custom level), made of one or more source levels."""

    def __init__(self, data, port):
        # a level with a "template" takes the keys of the manifest's level_templates[template] it
        # doesn't set itself (the districts of a city share most of theirs)
        if "template" in data:
            data = {**port.data["level_templates"][data["template"]], **data}
        self.data = data
        self.port = port
        self.name = data["name"]
        self.nick = data["nick"]
        # the source levels: its own, then the ones merged into it
        self.sources = list(data["sources"])
        self.what = data.get("what", self.name)
        self.folder = f"{port.levels_dir}/{self.name}"

    def get(self, key, default=None):
        return self.data.get(key, default)

    def __contains__(self, key):
        return key in self.data

    def __getitem__(self, key):
        return self.data[key]

    @property
    def dgo(self):
        return self.nick.upper()


class Port:
    def __init__(self, path):
        self.path = os.path.relpath(os.path.abspath(path), files.ROOT).replace(os.sep, "/")
        self.dir = os.path.dirname(self.path)
        self.data = read_jsonc(path)
        d = self.data
        self.name = d["name"]
        # the mark of the mod's edits and generated files (og:<mod>)
        self.tag = d["tag"]
        # the prefix of what the port names (continues, particle groups and callbacks...)
        self.prefix = d["prefix"]
        self.source = importlib.import_module(f"level_port.games.{d['source_game']}")
        self.target = importlib.import_module(f"level_port.games.{d['target_game']}")
        self.pair = importlib.import_module(
            f"level_port.convert.{d['source_game']}_{d['target_game']}")
        self.story = self.source.Story(**d.get("story", {}))
        paths = d["paths"]
        self.levels_dir = paths["levels"]
        self.models_dir = paths["models"]
        self.code_dir = paths["code"]
        self.levels = [Level(ld, self) for ld in d["levels"]]
        self.by_name = {lv.name: lv for lv in self.levels}
        # source level -> our level
        self.level_map = {src: lv.name for lv in self.levels for src in lv.sources}
        # our level -> its hub: the level loaded first with it, and unloaded last, which holds what
        # it shares with its neighbors (a city's districts and its city-wide level: code, traffic)
        self.hubs = {lv.name: lv["hub"] for lv in self.levels if "hub" in lv}

    def get(self, key, default=None):
        return self.data.get(key, default)

    def __getitem__(self, key):
        return self.data[key]

    def level(self, name):
        return self.by_name[name]

    def port_file(self, name):
        """A file of the port's folder (next to its manifest)."""
        return f"{self.dir}/{name}"

    def rip(self, path):
        """A model ripped from the source game: <level>/<model>-lod0.glb."""
        return f"{self.source.RIPS}/{path}"

    @property
    def generated(self):
        """The mark of a generated file, for a one-line comment."""
        return f"GENERATED by scripts/level_port from {self.path}, edit the port."

    def generated_lines(self, width=100, lead=";; "):
        """The mark of a generated file, for a GOAL comment of several lines (with the mod's
        tag)."""
        words = f"{self.tag} {self.generated}".split()
        lines, line = [], lead
        for w in words:
            if len(line) + len(w) + (line != lead) > width:
                lines.append(line)
                line = lead
            line += ("" if line == lead else " ") + w
        lines.append(line)
        return lines


def nested(table, *keys):
    """table[k0][k1]... or None (for the manifest's tables keyed by source level, then name)."""
    for k in keys:
        if not isinstance(table, dict) or k not in table:
            return None
        table = table[k]
    return table
