;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-pshaft: the palace pillars: the palace lobby and the cable pillar.
("HJS.DGO"
 (
  "com-airlock-inner-ag.go"
  "hj2-com-elevator-ag.go"
  "hj2-pshaft.go"
  ))
