;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-pshaft: the palace pillars: the palace lobby and the cable pillar.
("HJS.DGO"
 (
  "hj2-airlock-inner-ag.go"
  "hj2-com-elevator-ag.go"
  "hj2-pshaft-part.o"
  "hj2-pshaft.go"
  ))
