;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-inda: Haven City's district ctyinda: the industrial section, by Vin's power station.
("HIA.DGO"
 (
  "hj2-propa-ag.go"
  "hj2-propa-damaged-ag.go"
  "hj2-propa-broken-ag.go"
  "hj2-vin-door-ctyinda-ag.go"
  "hj2-cty-guard-turret-ag.go"
  "hj2-cty-guard-turret-explode-ag.go"
  "hj2-inda.go"
  ))
