;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-mincan: the canyon behind the mountain's iris doors.
("HKK.DGO"
 (
  "hj2-mincan.go"
  ))
