"""Files: the repository root, JSON with comments, and writing generated files."""

import json
import os
import re
import sys

# the repository root (scripts/level_port/common/files.py), or, for the one-file executable a mod
# release ships (frozen: no repository around it), the working directory. __main__.py's --root
# sets it (a mod's data/ folder, when the extractor runs the port at install time).
ROOT = (os.getcwd() if getattr(sys, "frozen", False)
        else os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

_JSONC_TOKEN = re.compile(r'"(?:[^"\\]|\\.)*"|//[^\n]*|/\*.*?\*/', re.S)


def read_jsonc(path):
    """A JSON file that may hold // and /* */ comments (like the level .jsonc files)."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    return json.loads(_JSONC_TOKEN.sub(lambda m: m.group(0) if m.group(0)[0] == '"' else "", text))


# every file of this run's output, written or left as it was (repository-relative, "/" separated):
# what the port generates, kept out of git (__main__.py, write_ignore_block)
OUTPUTS = set()


def write_ignore_block(gitignore, tag, paths):
    """Keep generated files out of git: the block of a .gitignore between two lines naming the tag
    (added at its end the first time) lists these paths, anchored at the repository root. Returns
    True when the file changed."""
    begin = f"# {tag}: files generated by scripts/level_port (begin, rewritten by it)"
    end = f"# {tag}: files generated by scripts/level_port (end)"
    block = "\n".join([begin, *[f"/{p}" for p in sorted(paths)], end])
    text = open(gitignore, encoding="utf-8").read() if os.path.exists(gitignore) else ""
    if begin in text and end in text:
        new = text[:text.index(begin)] + block + text[text.index(end) + len(end):]
    else:
        new = text.rstrip("\n") + "\n\n" + block + "\n"
    if new == text:
        return False
    with open(gitignore, "w", encoding="utf-8", newline="") as f:
        f.write(new)
    return True


def write_if_changed(path, data):
    """Write a generated file only when its content changes (text is written as UTF-8 with the line
    ends it has). goalc's make rebuilds a level whenever one of its inputs is newer than its output,
    and the port rewrites every level it knows: an unchanged level keeps its date."""
    OUTPUTS.add(os.path.relpath(os.path.abspath(path), ROOT).replace(os.sep, "/"))
    if isinstance(data, str):
        data = data.encode("utf-8")
    if os.path.exists(path):
        with open(path, "rb") as f:
            if f.read() == data:
                return False
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)
    return True
