;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-forta: the fortress, behind its gate in the slums.
("HJI.DGO"
 (
  "hj2-fort-gate-ag.go"
  "hj2-forta.go"
  ))
