;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-forta: the fortress, behind its gate in the slums.
("HJI.DGO"
 (
  "hj2-fort-gate-ag.go"
  "hj2-forta.go"
  ))
