;; GENERATED by custom_assets/jak3/levels/havenj2/gen_havenj2_links.py, edit the script.
;; DGO definition file for hj2-caspad: the castle pad, above the dig.
("HJY.DGO"
 (
  "com-airlock-outer-ag.go"
  "air-train-ag.go"
  "jakc-highres-ag.go"
  "daxter-highres-ag.go"
  "particleman-ag.go"
  "hj2-cpad-elevator-ag.go"
  "hj2-caspad.go"
  ))
