;; GENERATED by scripts/level_port from custom_assets/jak3/ports/jak2-haven-city/port.jsonc, edit the port.
;; DGO definition file for hj2-caspad: the castle pad, above the dig.
("HJY.DGO"
 (
  "air-train-ag.go"
  "hj2-airlock-outer-ag.go"
  "hj2-cpad-elevator-ag.go"
  "elec-gate.o"
  "hj2-caspad-obs.o"
  "hj2-caspad-part.o"
  "hj2-caspad.go"
  ))
